amblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

# Serve static files during dev
urlpatterns = [
    path('__site-admin__/', admin.site.urls),
    # Include Python-Social-Auth URLs
    path('social/', include('social_django.urls', namespace='social')),
    # Include blog app URLs
    path('', include('blog.urls', namespace='blog')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('privacy-policy/', TemplateView.as_view(template_name='privacy_policy.html'), name='privacy-policy'),
    path('cookie-policy/', TemplateView.as_view(template_name='cookie_policy.html'), name='cookie-policy'),
    path('disclaimer/', TemplateView.as_view(template_name='disclaimer.html'), name='disclaimer'),
]

blog/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/update/<int:pk>/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/delete/<int:pk>/',views.PostDeleteView.as_view(), name='post-delete'),
    path('search/', views.SearchView.as_view(), name='post-search'),
    # The returns a list of posts filtered by tag slugs that meet the url slug.
    path('search/pre_search/<slug>/', views.SearchView.as_view(), name='post-pre-search'),
    path('<username>/drafts/', views.UserDraftListView.as_view(), name='user-post-list'),
    path('post/<int:pk>/comments/', views.CommentListView.as_view(), name='post-comments'),
    path('comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment-delete'),
    path('comment/update/<int:pk>/', views.CommentUpdateView.as_view(), name='comment-update'),
    path('post/publish/<int:pk>/', views.post_publish, name='post_publish'),
    path('tag/create/', views.TagCreateView.as_view(), name='tag-create'),
    path('tag/list/', views.TagListView.as_view(), name='tag-list'),
    path('tag/overview/<slug>/', views.TagOverviewView.as_view(), name='tag-overview'),
    path('tag/update/<slug>/', views.TagUpdateView.as_view(), name='tag-update'),
    path('tag/delete/<slug>/',views.TagDeleteView.as_view(), name='tag-delete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

blog/models.py
# django-cleanup app is used to delete images whenever the image field
# is changed.

import posixpath
import urllib

from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.files import File
from django.core.files.storage import default_storage
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

# Set user as the currently active user model.
User = get_user_model()


def post_photo_path(instance, filename):
    """
    Returns upload path depending on if the post has been assigned a pk.
    """
    if instance.pk is None:
        return 'post_pictures/tmp/{0}'.format(filename)
    return 'post_pictures/post_{0}/{1}'.format(instance.pk, filename)


def tag_photo_path(instance, filename):
    """
    Returns the upload path for tag images.
    """
    return 'tag_pictures/{0}/{1}'.format(instance.slug, filename)


class Tag(models.Model):
    """
    Model for topic tags.
    """
    name = models.CharField(max_length=100, unique=True)
    # Used for URLs
    slug = models.SlugField(allow_unicode=True, unique=True)
    subheading = models.TextField()
    # Callable upload path.
    image = models.ImageField(blank=True, upload_to=tag_photo_path)
    # WYSIWYG rich text editor field (CKEditor).
    overview = RichTextField()

    def save(self, *args, **kwargs):
        """
        Additonal to base, sets slug upon save.
        """
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:tag-overview', kwargs={'slug': self.slug})

    def __str__(self):
        """
        String representation of object.
        """
        return self.name


class Post(models.Model):
    """
    Model for posts.
    """
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=100, unique=True)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    subheading = models.TextField(blank=True, null=True)
    # Callable upload path.
    image = models.ImageField(blank=True, null=True, upload_to=post_photo_path)
    created_date = models.DateTimeField(default=timezone.now, editable=False)
    publish_date = models.DateTimeField(blank=True, null=True)
    edited_date = models.DateTimeField(blank=True, null=True)
    # WYSIWYG rich text editor field (CKEditor).
    text = RichTextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        """
        Additonal to base, saves the image in a dir that includes the post pk.
        """

        # In order to save the image in a directory named with the post pk,
        # the post must first be assigned a pk from the database (i.e. saved).
        # Therefore, when a post is first saved, the image is intially saved
        # in a tmp directory. It is then moved to a directory named with the
        # newly assigned post pk.

        # This action saves the record to the database which assigns a pk.
        # If the post has not been saved before, if the user has input an image
        # into the form, the image is saved to a tmp directory.
        super().save(*args, **kwargs)

        # If an image exists, check to see if the image is located in a tmp
        # directory. If yes, create a new directory using the post pk, move the
        # image, and remove the tmp directory.
        if (self.image and
                urllib.parse.urljoin(settings.MEDIA_URL, 'post_pictures/tmp')
                == posixpath.dirname(self.image.url)):

            # Store the tmp file path.
            tmp_file = self.image.name

            # Store the image filename.
            filename = posixpath.basename(tmp_file)

            # Open the image located in the tmp directory and call save on the
            # image field with the image data. As the post object now has a pk,
            # post_photo_path will return a path including the pk.
            with default_storage.open(tmp_file, 'rb') as f:
                data = File(f)
                self.image.save(filename, data, True)

            # Remove the tmp folder.
            default_storage.delete(tmp_file)

    def publish(self):
        """
        Saves the post, and sets publish date as the current date.
        """
        self.publish_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})

    def __str__(self):
        """
        String representation of object.
        """
        return self.title


class Comment(models.Model):
    """
    Model for comments.
    """
    post = models.ForeignKey(
        Post, related_name='comments', null=True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created_date = models.DateTimeField(default=timezone.now, editable=False)
    edited_date = models.DateTimeField(blank=True, null=True)
    text = models.TextField()

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.post.pk})

    def __str__(self):
        """
        String representation of object.
        """
        return self.text

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count
from django.db.models.functions import Lower
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import View, generic
from django.views.generic.detail import SingleObjectMixin

from . import forms, models


### Authentication checkers ###
class StaffRequiredMixin(UserPassesTestMixin):
    """
    Mixin to check if user is staff.
    """

    def test_func(self):
        return self.request.user.is_staff


### LANDING VIEWS ###
class LandingPage(generic.TemplateView):
    """
    Landing page displaying 4 most recent posts and 4 most posted topics.
    """
    template_name = 'blog/landing.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Add tags context with 4 most posted topics
        context['tags'] = models.Tag.objects.annotate(
            num_posts=Count('posts')).order_by('-num_posts')[:4]

        # Add posts context with 4 most recent posts
        context['posts'] = models.Post.objects.filter(
            publish_date__isnull=False).order_by('-publish_date')[:4]

        return context


### POST VIEWS ###
class PostCreateView(StaffRequiredMixin, SuccessMessageMixin,
                     generic.CreateView):
    """
    Post create view accessible by any user with staff privileges.
    """
    form_class = forms.PostForm
    model = models.Post

    # On success, display message on base template.
    success_message = "%(title)s was created successfully"

    def form_valid(self, form_class):
        """
        Additional to base, sets user as post author.
        """
        form_class.instance.author = self.request.user
        return super().form_valid(form_class)


class PostDetailView(View):
    """
    Post detail selects CBV depending on the request HTTP method (POST/GET).
    """

    def get(self, *args, **kwargs):
        """
        For GET method select PostDisplay as view.
        """
        view = PostDisplay.as_view()
        return view(self.request, *args, **kwargs)

    def post(self, *args, **kwargs):
        """
        For POST method select Comment as view.
        """
        view = Comment.as_view()
        return view(self.request, *args, **kwargs)


class PostDisplay(generic.DetailView):
    """
    GET method for PostDetailView. Displays post, comments and comment form.
    """
    model = models.Post

    def get_object(self):
        """
        Checks if post not published and user not author. Returns post object.
        """
        obj = super().get_object()
        if obj.publish_date is None and self.request.user != obj.author:
            raise PermissionDenied()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Add comments and comment form as additional context.
        context['form'] = forms.CommentForm
        context['comments'] = self.object.comments.order_by('-created_date')

        return context


class SearchView(generic.ListView):
    """
    List view of all posts with search, filter and sort functionality.
    """
    template_name = 'blog/search.html'
    context_object_name = "posts"
    paginate_by = 12
    search_form = forms.SearchPostForm

    def get_queryset(self):
        """
        Modifies queryset based on user input to form and returns.
        """
        form = self.search_form(self.request.GET)

        # If valid form data submitted (HTTP GET).
        if form.is_valid():

            # Obtain form data.
            tag_filter = form.cleaned_data['tag_input']
            post_filter = form.cleaned_data['post_input']
            order_by = form.cleaned_data['order_input']

            # Base queryset, filtered to show posts that have been published.
            queryset = models.Post.objects.filter(publish_date__isnull=False)

            # Chain queryset dependent on user search form input.
            if tag_filter is not None:
                queryset = queryset.filter(tags__name__iexact=str(tag_filter))
            if post_filter is not None:
                queryset = queryset.filter(title__icontains=post_filter)
            if order_by == '0':
                queryset = queryset.order_by('-publish_date')
            elif order_by == '1':
                queryset = queryset.order_by('publish_date')

            # Set search_form values so they are displayed on post-search render.
            self.search_form = form

        # If form data not submitted.
        else:
            # If URL contains a tag slug, filter queryset by the slug. This is
            # done if  the pre-search URL is used to access this view. This is
            # used if the user selects all posts from a tag detail page.
            # Set the search form tag value to show the tag on the page render.
            try:
                queryset = models.Post.objects.filter(publish_date__isnull=False).filter(
                    tags__slug__iexact=self.kwargs['slug']).order_by('-publish_date')

                self.search_form = self.search_form({
                    'tag_input': models.Tag.objects.get(slug=self.kwargs['slug']),
                    'order_input': 0
                })

            # If accessing the URL slug kwarg throws an exception (i.e. the
            # pre-search URL has not been used to access the view) set queryset
            # to return all publish posts with newest first.
            except:
                queryset = models.Post.objects.filter(
                    publish_date__isnull=False).order_by('-publish_date')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Add search form to context.
        context['search_form'] = self.search_form

        return context


class UserDraftListView(StaffRequiredMixin, generic.ListView):
    """
    List view of user's drafts with search, filter and sort functionality.
    """
    template_name = 'blog/user_draft_list.html'
    context_object_name = "posts"
    search_form = forms.SearchDraftForm
    paginate_by = 12

    def get_queryset(self):
        """
        Modifies queryset based on user input to form and returns.
        """
        username = self.kwargs['username']
        if not User.objects.filter(username=username).exists():
            raise Http404("User does not exist")
        else:
            if username != self.request.user.username:
                raise PermissionDenied()
            else:
                form = self.search_form(self.request.GET)

                # If valid form data submitted (GET).
                if form.is_valid():
                    # Obtain form data.
                    tag_filter = form.cleaned_data['tag_input']
                    post_filter = form.cleaned_data['post_input']
                    order_by = form.cleaned_data['order_input']

                    # Base queryset, filtered to show user posts that are not published.
                    queryset = models.Post.objects.filter(
                        publish_date__isnull=True).filter(author=self.request.user)

                    # Chain queryset dependent on user search form input.
                    if tag_filter is not None:
                        queryset = queryset.filter(tags__name__iexact=str(tag_filter))
                    if post_filter is not None:
                        queryset = queryset.filter(title__icontains=post_filter)
                    if order_by == '0':
                        queryset = queryset.order_by('-created_date')
                    elif order_by == '1':
                        queryset = queryset.order_by('created_date')

                    # Set search_form values so they are displayed on post-search render.
                    self.search_form = form

                # If form data not submitted, set queryset to return all user posts
                # that are not published with newest first.
                else:
                    queryset = models.Post.objects.filter(publish_date__isnull=True).filter(
                        author=self.request.user).order_by('-created_date')

                return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Add search form to context data.
        context['search_form'] = self.search_form

        return context


class PostUpdateView(StaffRequiredMixin, SuccessMessageMixin,
                     generic.UpdateView):
    """
    Post update accessible by user with staff privileges and is post author.
    """
    form_class = forms.PostForm
    model = models.Post

    # On success, display message on base template.
    success_message = "%(title)s was edited successfully"

    def get_object(self):
        """
        Returns post object if post exists and user is post author.
        """
        obj = get_object_or_404(self.model, pk=self.kwargs.get('pk'))
        if obj.author == self.request.user:
            return obj
        else:
            raise PermissionDenied()

    def form_valid(self, form_class):
        """
        Additional to base, sets post edited date to current date.
        """
        self.object.edited_date = timezone.now()
        return super().form_valid(form_class)


class PostDeleteView(StaffRequiredMixin, generic.DeleteView):
    """
    Post delete accessible by any user with staff privileges.
    """
    model = models.Post
    context_object_name = "post"

blog/templates/blog/_comment.html
<div class="row">

  <div class="col-2 col-sm-1 d-flex justify-content-center pt-1">
    <i class="fas fa-user"></i>
  </div>

  <div class="col pl-0">
    <p><strong>{{ comment.author.get_full_name }}</strong>
      <br>
      <span class="text-muted small">{{ comment.created_date }}
        {% if comment.edited_date %}Edited{% endif %}
      </span>
      <br>
      {{ comment.text }}
    </p>

    {% if request.user == comment.author %}
    <a class="btn btn-secondary btn-sm rounded-0 mb-3"
      href="{% url 'blog:comment-update' pk=comment.pk %}">Edit</a>
    {% endif %}
    {% if request.user == comment.author or request.user.is_staff %}
    <a class="btn btn-secondary btn-sm rounded-0 mb-3"
      href="{% url 'blog:comment-delete' pk=comment.pk %}">Delete</a>
    {% endif %}
  </div>

</div>

blog/templates/blog/_pagination.html
<div class="pagination mb-3">

  <span class="step-links">
    {% if page_obj.has_previous %}
    <a class="btn btn-secondary rounded-0" href="?page=1">&laquo; first</a>
    <a class="btn btn-dark rounded-0"
      href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <p class="current p-0">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </p>

    {% if page_obj.has_next %}
    <a class="btn btn-dark rounded-0"
      href="?page={{ page_obj.next_page_number }}">next</a>
    <a class="btn btn-secondary rounded-0"
      href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}

  </span>
</div>

blog/templates/blog/_post_reduced.html
<div class="col px-2 col-6 col-md-3 d-flex flex-column h-100" id="list">

  <a class="text-dark" href="{% url 'blog:post-detail' post.pk %}">

    <div class="thumbnail">
      <img class="p-0" src={% if post.image %}"{{ post.image.url }}"{% endif %}
        alt="">
    </div>

    <h1 class="m-0">{{ post.title }}</h1>

  </a>

  {% if post.publish_date %}
  <h2 class="m-0">{{ post.publish_date|date:"jS M Y" }}</h2>
  {% else %}
  <h2 class="m-0">Created date: {{ post.created_date }}</h2>
  {% endif %}

  <h3 class="mt-0">Tags:
    {% for tag in post.tags.all %}
    <a href="{% url 'blog:tag-overview' slug=tag.slug %}"
      class="badge badge-dark">{{ tag }}</a>
    {% endfor %}
  </h3>

  <p class="mb-2">{{ post.subheading }}</p>

</div>

blog/templates/blog/_tag_reduced.html
<div class="col px-2 col-6 col-md-3 d-flex flex-column h-100" id="list">

  <a class="text-dark" href="{% url 'blog:tag-overview' slug=tag.slug %}">

    <div class="thumbnail">
      <img class="p-0" src={% if tag.image %}"{{ tag.image.url }}"{% endif %}
        alt="">
    </div>

    <h1 class="m-0">{{ tag.name }}</h1>

  </a>

  <h2 class="mt-0">Number of posts: {{ tag.num_posts }}</h2>
  <p class="mb-2">{{ tag.subheading }}</p>

</div>

blog/templates/blog/comment_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<div class="py-3">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ comment }}"?</p>
    <input class="btn btn-dark rounded-0" type="submit" value="Confirm">
    <a class="btn btn-secondary rounded-0"
      href="{% url 'blog:post-detail' pk=comment.post.pk %}">Cancel</a>
  </form>
</div>

{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- App CSS -->
<link rel="stylesheet" href="{% static 'blog/css/master.css' %}">

<div class="px-lg-5 mx-lg-5 p-3">
  <div class="post-body px-lg-5 mx-lg-5">

    <div id="detail-heading">
      <h1>Edit comment</h1>
    </div>

    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <p>Created on: {{ comment.created_date }}
        {% if comment.edited_date %}
        <br>Edited on: {{ comment.edited_date }}
        {% endif %}
      </p>
      <button class="btn btn-dark rounded-0" type="submit" class="">Save
        changes</button>
      <a class="btn btn-secondary rounded-0"
        href="{% url 'blog:post-detail' pk=comment.post.pk %}">Cancel</a>
    </form>
  </div>
</div>

{% endblock %}

blog/templates/blog/comment_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- App CSS -->
<link rel="stylesheet" href="{% static 'blog/css/master.css' %}">

<div class="px-lg-5 mx-lg-5">
  <div class="px-lg-5 mx-lg-5">

    <div id="detail-heading">
      <a class="text-dark"
        href="{% url 'blog:post-detail' pk=view.kwargs.pk %}">
        <h1>{{ comments.1.post.title }}</h1>
      </a>
      <h2>All comments:</h2>
    </div>

    <div class="mb-3">
      {% for comment in comments %}
      {% include "blog/_comment.html" %}
      {% endfor %}
    </div>

    {% include "blog/_pagination.html" %}

  </div>
</div>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<div class="py-3">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ post }}"?</p>
    <input class="btn btn-dark rounded-0" type="submit" value="Confirm">
    <a class="btn btn-secondary rounded-0"
      href="{% url 'blog:post-detail' pk=post.pk %}">Cancel</a>
  </form>
</div>

{% endblock %}

blog/templates/blog/search.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<!-- App CSS -->
<link rel="stylesheet" href="{% static 'blog/css/master.css' %}">

<div class="px-lg-5 mx-lg-5">

  <form id="search-form" class="py-3 border-bottom" method="GET">
    {% csrf_token %}
    <div class="form-row">
      <div class="input-group col-12 mb-1">
        {{ search_form.post_input }}
        <div class="input-group-append">
          <input class="btn btn-outline-dark rounded-0 py-0" type="submit"
            value="Search">
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="input-group col-6">
        <div class="input-group-prepend">
          <span
            class="input-group-text rounded-0">{{ search_form.tag_input.label }}</span>
        </div>
        {{ search_form.tag_input }}
      </div>
      <div class="input-group col-6">
        <div class="input-group-prepend">
          <span
            class="input-group-text rounded-0">{{ search_form.order_input.label }}</span>
        </div>
        {{ search_form.order_input }}
      </div>
    </div>
  </form>

  <div id="list" class="row mx-n2 py-3">
    {% for post in posts %}
    {% include "blog/_post_reduced.html" %}
    {% endfor %}
  </div>

  {% include "blog/_pagination.html" %}

</div>

{% endblock %}

blog/templates/blog/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<div class="py-3">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ tag }}"?</p>
    <input class="btn btn-dark rounded-0" type="submit" value="Confirm">
    <a class="btn btn-secondary rounded-0"
      href="{% url 'blog:tag-overview' slug=tag.slug %}">Cancel</a>
  </form>
</div>

{% endblock %}

blog/templates/blog/tag_detail.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<!-- App CSS -->
<link rel="stylesheet" href="{% static 'blog/css/master.css' %}">

<div id="detail" class="px-lg-5 mx-lg-5">

  <div class="wide mt-3">
    <img src={% if tag.image %}"{{ tag.image.url }}"{% endif %} alt="">
  </div>

  <div class="px-lg-5 mx-lg-5 pb-3">

    <div id="detail-heading">
      <h1>{{ tag.name|safe }}</h1>
      <h2>{{ tag.subheading|safe }}</h2>
    </div>

    <div id="detail-text">
      {{ tag.overview|safe }}
    </div>

    {% if user.is_staff %}
    <a class="btn btn-dark rounded-0"
      href="{% url 'blog:tag-update' slug=tag.slug %}">Edit</a>
    <a class="btn btn-secondary rounded-0"
      href="{% url 'blog:tag-delete' slug=tag.slug %}">Delete</a>
    {% endif %}

  </div>

  <!-- Same formatting from landing page -->
  <div class="row m-0 border-top" id="landing">
    <h3 class="col-6 p-0 m-0 text-left">Recent posts:</h3>
    <h3 class="col-6 p-0 m-0 text-right"><a class="text-dark"
        href="{% url 'blog:post-pre-search' slug=tag.slug %}">All <i
          class="fas fa-angle-double-right"></i></a></h3>
  </div>

  <div class="row mx-n2 py-1">
    {% for post in post_list.all %}
    {% include "blog/_post_reduced.html" %}
    {% endfor %}
  </div>

</div>

{% endblock %}

blog/templates/blog/tag_form.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}

<!-- App CSS -->
<link rel="stylesheet" href="{% static 'blog/css/master.css' %}">

<div class="my-3">

  <div id="detail-heading">
    {% if tag %}
    <h1>Edit tag</h1>
    {% else %}
    <h1>New tag</h1>
    {% endif %}
  </div>

  <form id="entry" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <button type="submit" class="btn btn-dark rounded-0">Save</button>
    <a class="btn btn-secondary rounded-0"
      href=
        {% if tag %}
        "{% url 'blog:tag-overview' slug=tag.slug %}"
        {% else %}
        "{% url 'blog:landing' %}"
        {% endif %}
    >Cancel</a>
  </form>

</div>

{% endblock %}

blog/templates/blog/tag_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<!-- App CSS -->
<link rel="stylesheet" href="{% static 'blog/css/master.css' %}">

<div class="px-lg-5 mx-lg-5">

  <form id="search-form" class="py-3 border-bottom" method="GET">
    {% csrf_token %}
    <div class="form-row">
      <div class="input-group col-12 mb-1">
        {{ search_form.name_input }}
        <div class="input-group-append">
          <input class="btn btn-outline-dark rounded-0 py-0" type="submit"
            value="Search">
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="input-group col">
        <div class="input-group-prepend">
          <span
            class="input-group-text rounded-0">{{ search_form.order_input.label }}</span>
        </div>
        {{ search_form.order_input }}
      </div>
    </div>
  </form>

  <div id="list" class="row mx-n2 py-3">
    {% for tag in tags %}
    {% include "blog/_tag_reduced.html" %}
    {% endfor %}
  </div>

  {% include "blog/_pagination.html" %}

</div>

{% endblock %}

blog/templates/blog/user_draft_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<!-- App CSS -->
<link rel="stylesheet" href="{% static 'blog/css/master.css' %}">

<div class="px-lg-5 mx-lg-5">

  <form id="search-form" class="py-3 border-bottom" method="GET">
    {% csrf_token %}
    <div class="form-row">
      <div class="input-group col-12 mb-1">
        {{ search_form.post_input }}
        <div class="input-group-append">
          <input class="btn btn-outline-dark rounded-0 py-0" type="submit"
            value="Search">
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="input-group col-6">
        <div class="input-group-prepend">
          <span
            class="input-group-text rounded-0">{{ search_form.tag_input.label }}</span>
        </div>
        {{ search_form.tag_input }}
      </div>
      <div class="input-group col-6">
        <div class="input-group-prepend">
          <span
            class="input-group-text rounded-0">{{ search_form.order_input.label }}</span>
        </div>
        {{ search_form.order_input }}
      </div>
    </div>
  </form>

  <div id="list" class="row mx-n2 py-3">
    {% for post in posts %}
    {% include "blog/_post_reduced.html" %}
    {% endfor %}
  </div>

  {% include "blog/_pagination.html" %}

</div>

{% endblock %}