amblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

# Serve static files during dev
urlpatterns = [
    path('__site-admin__/', admin.site.urls),
    # Include Python-Social-Auth URLs
    path('social/', include('social_django.urls', namespace='social')),
    # Include blog app URLs
    path('', include('blog.urls', namespace='blog')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('privacy-policy/', TemplateView.as_view(template_name='privacy_policy.html'), name='privacy-policy'),
    path('cookie-policy/', TemplateView.as_view(template_name='cookie_policy.html'), name='cookie-policy'),
    path('disclaimer/', TemplateView.as_view(template_name='disclaimer.html'), name='disclaimer'),
]

blog/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/update/<int:pk>/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/delete/<int:pk>/',views.PostDeleteView.as_view(), name='post-delete'),
    path('search/', views.SearchView.as_view(), name='post-search'),
    # The returns a list of posts filtered by tag slugs that meet the url slug.
    path('search/pre_search/<slug>/', views.SearchView.as_view(), name='post-pre-search'),
    path('<username>/drafts/', views.UserDraftListView.as_view(), name='user-post-list'),
    path('post/<int:pk>/comments/', views.CommentListView.as_view(), name='post-comments'),
    path('comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment-delete'),
    path('comment/update/<int:pk>/', views.CommentUpdateView.as_view(), name='comment-update'),
    path('post/publish/<int:pk>/', views.post_publish, name='post_publish'),
    path('tag/create/', views.TagCreateView.as_view(), name='tag-create'),
    path('tag/list/', views.TagListView.as_view(), name='tag-list'),
    path('tag/overview/<slug>/', views.TagOverviewView.as_view(), name='tag-overview'),
    path('tag/update/<slug>/', views.TagUpdateView.as_view(), name='tag-update'),
    path('tag/delete/<slug>/',views.TagDeleteView.as_view(), name='tag-delete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

templates/about.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="pt-3 pb-1 px-lg-5 mx-lg-5" id="about">

  <h1>About me</h1>

  <div class="float-right pl-md-2 pb-2 pb-md-0"><img id="about-main"
      src="{% static 'website_pictures/MB2_MU_07_square.jpg' %}" alt=""></div>

  <p>Hello! Thank you for visiting my website. Its aim is to provide some
    interesting and thought provoking insights on the latest developments in
    climate change policies.</p>

  <p>We are in a pivotal time for climate change. The science underpinning the
    need for urgent action is now generally accepted, although with some notable
    exceptions. In the words of Mark Carney, the UN envoy for climate change and
    former governor of the Bank of England:</p>

  <div class="bg-grey px-3">

    <p><em>“There is a growing international consensus that climate change is
        unequivocal. Many of the changes in our world since the 1950s are
        without precedent: not merely over decades but over millennia. Research
        tells us with a high degree of confidence that:</em></p>

    <ul><em>

        <li>In the Northern Hemisphere the last 30 years have been the warmest
          since Anglo-Saxon times; indeed, eight of the ten warmest years on
          record in the UK have occurred since 2002;</li>

        <li>Atmospheric concentrations of greenhouse gases are at levels not
          seen in 800,000 years; and</li>

        <li>The rate of sea level rise is quicker now than at any time over the
          last 2 millennia.</li>

    </ul></em>

    <p class="mb-0"><em>Evidence is mounting of man’s role in climate change.
        Human drivers are judged extremely likely to have been the dominant
        cause of global warming since the mid-20th century. While natural
        fluctuations may mask it temporarily, the underlying human-induced
        warming trend of two-tenths of a degree per decade has continued
        unabated since the 1970s.”</em></p>

  </div>

  <p><small>(Quote from speech given by Mark Carney to Lloyd’s of London 29
      September 2015)</small></p>

  <p>Although changes in the behaviour of individuals are important, this is
    dependent on many factors, some of which cannot be predicted (for example,
    the reduction in flights due to Covid 19). Therefore, I believe that
    behaviour changes need to be driven by thoughtful government policies and
    well drafted laws. During my career, I’ve worked with policy makers and
    regulators and I was appointed as an expert reviewer of the UN’s
    Intergovernmental Panel on Climate Change’s Sixth Assessment Report,
    concentrating on the impact of the business sector on the fight against
    climate change.</p>

  <p>As with any scientific issue, there is disagreement and debate about
    climate change. But modelling and research point to the probability that the
    acceleration of climate warming since the 1970s is man-made. Doing nothing
    to slow down this acceleration will have catastrophic consequences for the
    planet and its human population. So even if you are not convinced by the
    science, doing nothing is not an option. If there is a small chance that the
    projections are correct, can we afford not to do something about it?</p>

  <h2>Connect with me <a
      href="https://www.linkedin.com/in/alison-mungall-13617b28/"><i
        class="fab fa-linkedin"></i></a></h2>

</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>

  <meta charset="utf-8">
  <!-- Viewport meta tag required for responsiveness -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
    crossorigin="anonymous">
  <!-- Google fonts -->
  <link
    href="https://fonts.googleapis.com/css2?family=Fira+Sans+Extra+Condensed:wght@300;400;500&family=Fira+Sans:wght@300;400;700&display=swap"
    rel="stylesheet">
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/3b228b1529.js"
    crossorigin="anonymous"></script>
  <!-- Website CSS -->
  <link rel="stylesheet" href="{% static 'css/master.css' %}">
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png"
    href="{% static 'website_pictures/favicon.ico.png' %}">

  <title>Alison's Blog</title>

</head>

<body>

  <div class="container">

    {% if user.is_authenticated %}
    <p class="mr-0" id="user-display">Welcome {{ user.first_name }}</p>
    {% endif %}

    <nav
      class="navbar navbar-expand-md navbar-light justify-content-end border-bottom border-dark">

      <!-- Brand -->
      <a class="navbar-brand mr-auto d-flex align-items-center brand"
        href="{% url 'blog:landing' %}">
        <span id="primary">Alison Mungall</span>
        <span class="collapse navbar-collapse">
          <span id="pipe">|</span>
          <span id="secondary">A blog about<br>sustainability</span>
        </span>
      </a>

      <!-- Links -->
      <div class="collapse navbar-collapse ml-auto flex-grow-0"
        id='toggle-burger'>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post-create' %}">Create
              post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:tag-create' %}">Create
              topic</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"
              href="{% url 'blog:user-post-list' user.username %}">Drafts</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:logout' %}">Sign out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link"
              href="{% url 'social:begin' 'linkedin-oauth2' %}">Sign in</a>
          </li>
          {% endif %}
        </ul>
      </div>

      <!-- Search -->
      <a class="nav-item nav-link" href="{% url 'blog:post-search' %}"><i
          class="fas fa-search"></i></a>

      <!-- Button -->
      <button class="nav-item navbar-toggler" type="button"
        data-toggle="collapse" data-target="#toggle-burger"
        aria-controls="toggle-burger" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    </nav>

    {% if messages %}
    <div class="alert alert-light alert-dismissible fade show" role="alert">
      {% for message in messages %}
      <p{% if message.tags %} class="{{ message.tags }}" role="alert"
        {% endif %}>{{ message }}</p>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert"
        aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}

    {% block content %}

    {% endblock %}

    <div class="border-top mb-1 d-flex flex-column align-items-center">
      <p class="footer p-0">Website created by Greg Mungall <a
          href="https://www.linkedin.com/in/gregmungall/"><i
            class="fab fa-linkedin"></i></a></p>
      <p class="footer p-0">
        <small>
          <a class="text-muted mx-1" href="{% url 'privacy-policy' %}">Privacy
            policy</a>
          <a class="text-muted mx-1" href="{% url 'cookie-policy' %}">Cookie
            policy</a>
          <a class="text-muted mx-1"
            href="{% url 'disclaimer' %}">Disclaimer</a>
        </small>
      </p>
    </div>


  </div>

  <!-- jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

</body>

</html>

templates/cookie_policy.html
{% extends "base.html" %}
{% block content %}

<div class="pt-3 pb-1 px-lg-5 mx-lg-5" id="info-pages">

  <h1>Alison Mungall’s blog Cookie Policy</h1>
  <p>This is the Cookie Policy for Alison Mungall's blog, accessible from <a
      href="https://www.alison-mungall.co.uk">www.alison-mungall.co.uk</a>. This
    Cookie Policy is effective from 2nd November 2020.</p>
  <p>This website is the personal blog of me, Alison Mungall. It does not
    generate any form of revenue and is a purely personal activity. The data
    controller is also me. We only collect essential personal information and
    strictly necessary cookies required to allow the website to function. This
    data would not be passed on to a third party without first seeking written
    permission from the data owner.</p>

  <h2>What Are Cookies</h2>
  <p>As is common practice with almost all websites, this site uses cookies.
    These are small pieces of information, normally consisting of just letters
    and numbers, which online services provide when users visit them. Software
    on the user's device (for example a web browser) can store cookies and send
    them back to the website next time they visit.</p>
  <p>There are two types of cookies, session and persistent. Cookies that expire
    at the end of a browser session (normally when a user exits their browser)
    are called session cookies. Cookies that can be stored for longer are called
    ‘persistent cookies’. We only use session cookies.</p>

  <h2>How We Use Cookies</h2>
  <p>We only use first-party, strictly necessary, session cookies for
    authentication and security.</p>

  <h2>Disabling Cookies</h2>
  <p>You can prevent the setting of cookies by changing the settings on your
    browser (see your browser Help for how to do this). Be aware that disabling
    cookies will affect the functionality of this website.</p>

  <h2>The Cookies We Set</h2>
  <ul>
    <li><strong>Authentication related cookies.</strong> When you sign in to the
      website, we store a session ID cookie. This is used to identify that
      you’ve signed in so you can access restricted features and areas of the
      website. This is a first-party, strictly necessary, session cookie which
      will be deleted at the end of the session (normally when you exit your
      browser or sign out).
    </li>
    <li><strong>Security-related cookies.</strong>We use Cross-Site Request
      Forgery (CSRF) tokens (cookies) to protect users from CSRF attacks. CSRF
      is an attack that forces a user to perform unwanted actions on a website.
      This is a first-party, strictly necessary, session cookie which will be
      deleted at the end of the session (normally when you exit your browser).
    </li>
  </ul>

  <h2>More information</h2>
  <p>If you are still looking for more information on how we use cookies, than
    please email us at <a
      href="mailto:alisonmungallblog@gmail.com">alisonmungallblog@gmail.com</a>.
  </p>

</div>

{% endblock %}

templates/disclaimer.html
{% extends "base.html" %}
{% block content %}

<div class="pt-3 pb-1 px-lg-5 mx-lg-5" id="info-pages">

  <h1>Example h1</h1>
  <h2>Example h2</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
    non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>

</div>

{% endblock %}

templates/privacy_policy.html
{% extends "base.html" %}
{% block content %}

<div class="pt-3 pb-1 px-lg-5 mx-lg-5" id="info-pages">

  <h1>Alison Mungall’s blog Privacy Policy</h1>
  <p>This is the Privacy Policy for Alison Mungall's blog, accessible from <a
      href="https://www.alison-mungall.co.uk">www.alison-mungall.co.uk</a>. This
    Privacy Policy is effective from 2nd November 2020.</p>
  <p>This website is the personal blog of me, Alison Mungall. It does not
    generate any form of revenue and is a purely personal activity. The data
    controller is also me. We only collect essential personal information and
    strictly necessary cookies required to allow the website to function. This
    data would not be passed on to a third party without first seeking written
    permission from the data owner.</p>
  <p>For any questions regarding this policy, please email <a
      href="mailto:alisonmungallblog@gmail.com">alisonmungallblog@gmail.com</a>.
  </p>

  <h2>The type of personal information we collect</h2>
  <p>We currently collect and process the following personal information:</p>
  <ul>
    <li>Your first name.</li>
    <li>Your last name.</li>
    <li>The IP address you used to access the website.</li>
    <li>Information about your visit such as the pages accessed.</li>
    <li>Information requested and the date and time of the request.</li>
    <li>The source of your access to the website (e.g. the website or URL (link)
      which referred you to the website).</li>
    <li>Browser version and operating system.</li>
    <li>Session ID cookies for authentication purposes. This is a first-party,
      strictly necessary, session cookie which will be deleted at the end of the
      session (normally when you exit your browser or sign out). See our <a
        href="{% url 'cookie-policy' %}">cookie policy</a> for more information.
    </li>
  </ul>

  <h2>How we get the personal information and why we have it</h2>
  <p>Most of the personal information processed by the website is provided
    directly by you when/if you sign in to the website using LinkedIn.</p>
  <p>Personal information is also indirectly received from the third party
    server provider, called Amazon Web Services, used to host the website. The
    privacy policy of Amazon Web Services is available here: <a
      href="https://aws.amazon.com/privacy/">https://aws.amazon.com/privacy/</a>.
  </p>
  <p>The information that you have given is used to:</p>
  <ul>
    <li>To register you as a user. The personal data you provide when you
      register is used when/if you comment on a post.</li>
    <li>To identify that you’ve signed in so you can access restricted features
      and areas of the website.</li>
    <li>To provide and maintain the website, including to monitor the usage of
      our site.</li>
  </ul>
  <p>We collect basic personal information for administrative purposes only.
    This information would not be passed on to a third party without first
    seeking written permission from the data owner. It would not be passed on to
    anyone else for the purposes of sales, advertising or marketing.</p>
  <p>Under the General Data Protection Regulation (GDPR), the lawful bases we
    rely on for processing this information is <strong>your consent</strong>.
    You can remove your consent at any time. You can do this by contacting <a
      href="mailto:alisonmungallblog@gmail.com">alisonmungallblog@gmail.com</a>.
  </p>

  <h2>How we store your personal information</h2>
  <p>Your information is securely stored by Amazon Web Services in London, UK.
  </p>
  <p>Your personal data will be kept only for as long as is necessary for the
    purposes set out in this Privacy Policy. We will then dispose of your
    information by deleting the data from the servers.</p>

  <h2>Your data protection rights</h2>
  <p>Under data protection law, you have rights including:</p>
  <p><strong>Your right of access</strong> - You have the right to ask us for
    copies of your personal information.</p>
  <p><strong>Your right to rectification</strong> - You have the right to ask us
    to rectify personal information you think is inaccurate. You also have the
    right to ask us to complete information you think is incomplete.</p>
  <p><strong>Your right to erasure</strong> - You have the right to ask us to
    erase your personal information in certain circumstances.</p>
  <p><strong>Your right to restriction of processing</strong> - You have the
    right to ask us to restrict the processing of your personal information in
    certain circumstances.</p>
  <p><strong>Your right to data portability</strong> - You have the right to ask
    that we transfer the personal information you gave us to another
    organisation, or to you, in certain circumstances.</p>
  <p>You are not required to pay any charge for exercising your rights. If you
    make a request, we have one month to respond to you.</p>
  <p>Please contact us at <a
      href="mailto:alisonmungallblog@gmail.com">alisonmungallblog@gmail.com</a>
    if you wish to make a request.</p>

  <h2>Children’s privacy</h2>
  <p>This Site is not for or directed towards children. We do not intend to and
    will not knowingly collect any personal information from children under the
    age of 13; children under the age of 13 are prohibited from using the Site
    without parent/guardian supervision. If we learn that we have collected
    information from a child under the age of 13, we will remove that
    information immediately and delete it from our servers (subject to
    applicable law and this Policy). If you believe User Content from a child
    under the age of 13 has been posted to the Site, please notify us by
    emailing <a
      href="mailto:alisonmungallblog@gmail.com">alisonmungallblog@gmail.com</a>.
  </p>

  <h2>How to complain</h2>
  <p>If you have any concerns about our use of your personal information, you
    can make a complaint to us at <a
      href="mailto:alisonmungallblog@gmail.com">alisonmungallblog@gmail.com</a>.
  </p>
  <p>You can also complain to the ICO if you are unhappy with how we have used
    your data.</p>
  <p>The ICO’s address:</p>
  <p>
    Information Commissioner’s Office<br>
    Wycliffe House<br>
    Water Lane<br>
    Wilmslow<br>
    Cheshire<br>
    SK9 5AF<br>
  </p>
  <p>Helpline number: 0303 123 1113</p>
  <p>ICO website: <a href="https://www.ico.org.uk">https://www.ico.org.uk</a>
  </p>

</div>

{% endblock %}